version: "3.8"

services:
  redis:
    image: redis:7.4.5-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/config/redis.conf
    command: ["redis-server", "/config/redis.conf"]
    networks:
      - vaultui-networks
  vaultui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      REDIS_ADDR: ${REDIS_ADDR}
      REDIS_PASS: ${REDIS_PASS}
      SQL_PATH: ${SQL_PATH}
    networks:
      - vaultui-networks
    command: "./vaultui"

networks:
  vaultui-networks:
    driver: bridge
